const data = {
  products: [
    {
      _id: 1,
      name: "fender F310",
      category: "Acoustic Guitar",
      image: "/image/fender_f310.jpg",
      price: 9999,
      Brand: "fender",
      official: "https://www.fender.com",
      rating: 2,
      description: "",
      numreviews: 0,
      stock: 23,
    },
    {
      _id: 2,
      name: "Kadence Frontier",
      category: "Acoustic Guitar",
      image: "/image/KadenceFrontier.jpeg",
      price: 9999,
      Brand: "Kadence",
      official: "https://kadence.in",
      rating: 2.4,
      description: "",
      numreviews: 0,
      stock: 0,
    },
    {
      _id: 3,
      name: "Yamaha FS100C",
      category: "Acoustic Guitar",
      image: "/image/YamahaFS100C.jpg",
      price: 9999,
      Brand: "Yamaha",
      official:
        "https://usa.yamaha.com/products/musical_instruments/guitars_basses/index.html",
      rating: 0.7,
      description: "",
      numreviews: 0,
      stock: 43,
    },
    {
      _id: 4,
      name: "Yamaha F280",
      category: "Acoustic Guitar",
      image: "/image/yamaha_f280.jpg",
      price: 9999,
      Brand: "Yamaha",
      official:
        "https://usa.yamaha.com/products/musical_instruments/guitars_basses/index.html",
      rating: 5,
      description: "",
      numreviews: 10,
      stock: 0,
    },
  ],
};

export default data;
